// Copyright © 2026 Chloe Bolland
// contact chloe@mammoththoughts.com if you wish to use, publish or reproduce this game or any part of it in any way

// minespike.sprite.js — GENERATED by scripts/build-sprites.mjs from assets/sprites/minespike.svg
// Do not edit by hand. Re-run:  node scripts/build-sprites.mjs
export const minespikeSprite = {
  "name": "minespike",
  "duration": 2400,
  "viewBox": [
    0,
    0,
    264.58333,
    264.58333
  ],
  "layers": [
    {
      "id": "mine-spike",
      "path": "m 132.57838,255.52975 -10.11594,-10.04166 -10.78576,-122.64964 4.40059,-71.943121 13.71239,-45.6704786 14.91683,45.6905566 5.58481,70.431533 -6.40093,122.15283 z",
      "fill": "#f6ff55"
    }
  ]
};
