// ufo.sprite.js — GENERATED by scripts/build-sprites.mjs from assets/sprites/ufo.svg
// Do not edit by hand. Re-run:  node scripts/build-sprites.mjs
export const ufoSprite = {
  "name": "ufo",
  "duration": 2400,
  "viewBox": [
    0,
    0,
    200,
    200
  ],
  "layers": [
    {
      "id": "engine-glow",
      "path": "M 46 122 A 54 12 0 1 0 154 122 A 54 12 0 1 0 46 122 Z",
      "fill": "team.primary",
      "pivot": [
        100,
        122
      ],
      "keyframes": [
        {
          "t": 0,
          "scale": 0.9,
          "opacity": 0.6
        },
        {
          "t": 0.5,
          "scale": 1.15,
          "opacity": 1
        },
        {
          "t": 1,
          "scale": 0.9,
          "opacity": 0.6
        }
      ]
    },
    {
      "id": "saucer-rim",
      "path": "M 8 106 A 92 28 0 1 0 192 106 A 92 28 0 1 0 8 106 Z",
      "fill": "team.secondary",
      "pivot": [
        100,
        106
      ],
      "minRadius": 6,
      "keyframes": [
        {
          "t": 0,
          "ty": 0
        },
        {
          "t": 0.5,
          "ty": -2.5
        },
        {
          "t": 1,
          "ty": 0
        }
      ]
    },
    {
      "id": "saucer-disc",
      "path": "M 12 104 A 88 26 0 1 0 188 104 A 88 26 0 1 0 12 104 Z",
      "fill": "#b8bec8",
      "pivot": [
        100,
        104
      ],
      "keyframes": [
        {
          "t": 0,
          "ty": 0
        },
        {
          "t": 0.5,
          "ty": -2.5
        },
        {
          "t": 1,
          "ty": 0
        }
      ]
    },
    {
      "id": "saucer-ports",
      "path": "M 35 104 A 5 5 0 1 0 45 104 A 5 5 0 1 0 35 104 Z M 65 110 A 5 5 0 1 0 75 110 A 5 5 0 1 0 65 110 Z M 95 112 A 5 5 0 1 0 105 112 A 5 5 0 1 0 95 112 Z M 125 110 A 5 5 0 1 0 135 110 A 5 5 0 1 0 125 110 Z M 155 104 A 5 5 0 1 0 165 104 A 5 5 0 1 0 155 104 Z",
      "fill": "team.secondary",
      "minRadius": 10,
      "keyframes": [
        {
          "t": 0,
          "ty": 0
        },
        {
          "t": 0.5,
          "ty": -2.5
        },
        {
          "t": 1,
          "ty": 0
        }
      ]
    },
    {
      "id": "saucer-dome",
      "path": "M 56 100 A 44 36 0 0 1 144 100 Z",
      "fill": "#9fd0e0",
      "keyframes": [
        {
          "t": 0,
          "ty": 0
        },
        {
          "t": 0.5,
          "ty": -2.5
        },
        {
          "t": 1,
          "ty": 0
        }
      ]
    }
  ]
};
